# Server Configuration
server:
  host: "127.0.0.1"  # SECURITY: Bind to localhost only, not all interfaces
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"

# OpenAI Configuration
openai:
  api_key: "${OPENAI_API_KEY}"  # From environment variable
  model: "gpt-4o-mini"
  temperature: 0.7
  top_p: 1.0
  max_tokens: 4096
  stream: true
  system_prompt: |
    You are a helpful AI assistant. You provide clear, accurate, and helpful responses.
    When using tools, explain what you're doing and why.

# MCP (Model Context Protocol) Configuration
mcp:
  enabled: true
  servers: []
  # Example server configuration following 2025 best practices:
  # servers:
  #   - name: "example-server"
  #     url: "http://127.0.0.1:3000"  # Localhost only for security
  #     transport: "streamable-http"   # Modern transport
  #     timeout: 30
  #     auth_token: "${MCP_AUTH_TOKEN}"  # Optional authentication
  #     bind_localhost: true           # Security enforcement

# Logging Configuration
logging:
  level: "INFO"
  format: "json"

# Request Configuration
request:
  timeout: 60  # seconds
  max_retries: 3
  retry_delay: 1  # seconds
